apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: n8n
data:
  N8N_HOST: "0.0.0.0"
  N8N_PORT: "5678"
  N8N_PROTOCOL: "http"
  WEBHOOK_URL: "http://localhost:30678/"
  GENERIC_TIMEZONE: "Asia/Seoul"
  N8N_USER_MANAGEMENT_DISABLED: "true"
  N8N_BASIC_AUTH_ACTIVE: "true"
  N8N_METRICS: "false"
  N8N_LOG_LEVEL: "info"
  N8N_EXECUTE_IN_SAME_PROCESS: "true" 